version: '3.8'
services:
  bot:
    build: .
    container_name: 2mov-tg-bot
    restart: unless-stopped
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - MONGO_URI=mongodb://127.0.0.1:27017
      - MODE=telegram
